"""
CircuitSense — Fault Diagnosis Page
Symptom input → Rule engine + Correlation + Gemini AI → Actionable diagnostic chain.
"""

import streamlit as st
import time
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine.gemini_client import diagnose_fault

st.set_page_config(page_title="Fault Diagnosis — CircuitSense", layout="wide", initial_sidebar_state="collapsed")

from nav import render_top_nav
render_top_nav()

def _show_export(symptoms: str, diagnosis: str):
    """Show a download button for the diagnostic report."""
    from datetime import datetime
    report = f"""# CircuitSense — Diagnostic Report
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Symptoms Reported
{symptoms}

## Diagnosis
{diagnosis}

---
*Report generated by CircuitSense AI Test Co-pilot*
"""
    st.download_button(
        "Export Diagnostic Report",
        data=report,
        file_name=f"circuitsense_diagnosis_{datetime.now().strftime('%Y%m%d_%H%M')}.md",
        mime="text/markdown",
        use_container_width=True,
    )

st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
    
    .stApp { background-color: #FFFFFF; font-family: 'Inter', sans-serif; }
    
    h1, h2, h3, h4, h5, h6 { color: #0F172A !important; font-weight: 700 !important; letter-spacing: -0.5px; }
    p, span, div { color: #334155; }
    
    .stApp [data-testid="stMarkdownContainer"] h3 {
        margin-top: 1.5rem !important;
        margin-bottom: 0.5rem !important;
        font-size: 1.3rem !important;
    }
    
    .top-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 24px;
        margin-top: -16px;
    }
    .page-title {
        font-size: 2.2rem;
        font-weight: 800;
        color: #0F172A;
        margin: 0;
    }
    
    [data-testid="stHorizontalBlock"] { gap: 16px !important; }
    
    [data-testid="block-container"] {
        padding-top: 2rem !important;
        padding-bottom: 2rem !important;
        max-width: 1240px;
    }
    
    /* Diagnostic Report Styling */
    .diagnostic-report {
        background-color: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 8px;
        padding: 32px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        margin-top: 16px;
        margin-bottom: 24px;
        color: #1E293B;
        line-height: 1.6;
    }
    
    .diagnostic-report h1, .diagnostic-report h2, .diagnostic-report h3 {
        margin-top: 0;
        border-bottom: 2px solid #F1F5F9;
        padding-bottom: 8px;
        margin-bottom: 16px;
    }
    
    .verdict-box {
        margin-top: 32px;
        padding: 24px;
        border-radius: 8px;
        border-left: 4px solid #0F172A;
        background-color: #F8FAFC;
    }
    
    .verdict-title {
        font-size: 0.9rem;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-weight: 700;
        color: #64748B;
        margin-bottom: 8px;
    }
    
    .verdict-text {
        font-size: 1.5rem;
        font-weight: 800;
        color: #0F172A;
        line-height: 1.3;
    }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="top-header">
    <h1 class="page-title">Fault Diagnosis</h1>
</div>
""", unsafe_allow_html=True)
st.markdown("Describe the symptoms you're observing and get **step-by-step diagnostic chains** — not just a label, but what to measure next and what to expect.")
st.markdown("<br>", unsafe_allow_html=True)

# --- Context awareness ---
has_board = "board_context" in st.session_state
has_anomaly = "anomaly_results" in st.session_state
has_correlation = "correlation_results" in st.session_state

context_badges = []
if has_board:
    context_badges.append("Board Analysis")
if has_anomaly:
    context_badges.append("Anomaly Data")
if has_correlation:
    context_badges.append("Correlations")

if context_badges:
    context_str = ' • '.join(context_badges)
    st.markdown(f"""
    <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; padding: 12px 16px; border-radius: 8px; display: flex; align-items: center; gap: 8px; margin-bottom: 24px;">
        <div style="width: 8px; height: 8px; background-color: #3B82F6; border-radius: 50%;"></div>
        <span style="font-size: 0.9rem; color: #334155; font-weight: 500;">Using context from: <span style="color: #0F172A; font-weight: 600;">{context_str}</span> — diagnosis will be board-specific.</span>
    </div>
    """, unsafe_allow_html=True)
else:
    st.markdown("""
    <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; padding: 12px 16px; border-radius: 8px; display: flex; align-items: center; gap: 8px; margin-bottom: 24px;">
        <span style="font-size: 0.9rem; color: #64748B;">Tip: Upload a BOM and test data on other pages first for context-aware diagnostics.</span>
    </div>
    """, unsafe_allow_html=True)

# Suggested symptom buttons
st.markdown("### Common Symptoms (Click to Use)")
suggested = [
    "Output voltage is 4.2V instead of 5V, and there's visible ripple on the oscilloscope",
    "Board powers on but the MCU is not responding, clock signal looks unstable",
    "Voltage regulator is extremely hot after 5 minutes under load",
    "Intermittent resets occurring randomly during operation",
    "3.3V rail is noisy, I2C communication has checksum errors",
]

# Use columns for  suggested symptom buttons
cols = st.columns(2)

def set_symptom(sym):
    st.session_state.symptoms_input = sym

for i, sym in enumerate(suggested):
    with cols[i % 2]:
        st.button(f"{sym[:80]}...", key=f"sym_{i}", use_container_width=True, on_click=set_symptom, args=(sym,))

st.markdown("<br>", unsafe_allow_html=True)

# Symptom input
st.markdown("### Describe Your Symptoms")
symptoms = st.text_area(
    "What are you observing?",
    key="symptoms_input",
    height=100,
    placeholder="e.g., Output voltage is low at 4.2V instead of 5V, ripple is 150mV peak-to-peak, regulator U1 is hot to touch...",
    label_visibility="collapsed"
)

# Diagnose button
if st.button("Run Diagnosis", use_container_width=True):
    if not symptoms.strip():
        st.warning("⚠️ **Please describe the observed symptoms before running a diagnosis.**")
        st.stop()

    # Build context strings
    board_context = st.session_state.get("board_context", "")
    
    anomaly_context = ""
    if has_anomaly:
        results = st.session_state["anomaly_results"]
        anomaly_context = f"Anomaly detection found {results['anomaly_count']} anomalies out of {results['total_points']} data points using {results['method']}."
        if results.get("feature_contributions"):
            anomaly_context += "\nKey anomalous features:\n"
            for idx, contribs in list(results["feature_contributions"].items())[:3]:
                for feat, info in contribs.items():
                    if isinstance(info, dict):
                        anomaly_context += f"  - {feat}: actual={info.get('actual_value', 'N/A')}, mean={info.get('mean', 'N/A')}\n"

    correlation_context = ""
    if has_correlation:
        corr_results = st.session_state["correlation_results"]
        if corr_results.get("linked_failures"):
            correlation_context = "Correlated failure groups found:\n"
            for group in corr_results["linked_failures"]:
                correlation_context += f"  - {group['type']}: {', '.join(group['linked_parameters'])} ({group['confidence']} confidence)\n"
                correlation_context += f"    Explanation: {group['explanation']}\n"

    # Run diagnosis
    # Run diagnosis with simulated "Thought Process" for hackathon wow-factor
    with st.status("Initializing CircuitSense AI Diagnostic Agent...", expanded=True) as status:
        time.sleep(0.8)
        if has_board:
            status.update(label="Analyzing Board Topology & Components...", state="running")
            st.write("✓ BOM context loaded: Extracting power distribution paths...")
            time.sleep(1.2)
            st.write("✓ Applying heuristic engineering rules to identified regulators...")
            time.sleep(0.8)
        
        if has_anomaly or has_correlation:
            status.update(label="Cross-referencing Telemetry & Correlation Data...", state="running")
            st.write("✓ Analyzing statistical anomalies in test data...")
            time.sleep(1.0)
            if has_correlation:
                st.write("✓ Incorporating detected anomalies into diagnostic scope...")
                time.sleep(0.9)
                
        status.update(label="Synthesizing Diagnostic Chain with Mistral-Large...", state="running")
        st.write("✓ Querying electronics failure knowledge base...")
        
        diagnosis = diagnose_fault(
            symptoms=symptoms,
            board_context=board_context,
            anomaly_context=anomaly_context,
            correlation_context=correlation_context,
        )
        status.update(label="Diagnosis Complete", state="complete", expanded=False)

    # Display result with explainability badges
    st.markdown("### Diagnosis Result")
    
    badge_list = [("AI-reasoned", "destructive")]
    confidence_score = 0
    
    if has_board:
        badge_list.append(("Board-context aware", "default"))
        confidence_score += 2
    if has_anomaly:
        badge_list.append(("ML-data informed", "secondary"))
        confidence_score += 1
    if has_correlation:
        badge_list.append(("Correlation-aware", "outline"))
        confidence_score += 1
        
    confidence_level = "HIGH" if confidence_score >= 3 else "MEDIUM" if confidence_score == 2 else "LOW"
    badge_html = ""
    for badge, color_class in badge_list:
        bg_col = "#FEE2E2" if color_class == "destructive" else "#DBEAFE" if color_class == "secondary" else "#F1F5F9"
        text_col = "#991B1B" if color_class == "destructive" else "#1E40AF" if color_class == "secondary" else "#334155"
        border = "1px solid #E2E8F0" if color_class == "outline" else "none"
        if color_class == "outline":
            bg_col = "transparent"
        badge_html += f'<span style="background-color: {bg_col}; color: {text_col}; border: {border}; padding: 4px 10px; border-radius: 9999px; font-size: 0.75rem; font-weight: 500; margin-right: 8px;">{badge}</span>'
        
    st.markdown(f'<div style="margin-bottom: 16px;">{badge_html}</div>', unsafe_allow_html=True)
    st.markdown(f"**System Confidence Engine:** {confidence_level} (Derived from {confidence_score} context layers)")
    
    if confidence_score <= 1:
         st.warning("⚠️ *This diagnosis is speculative due to missing design or measurement context.*")
    
    def _render_styled_diagnosis(raw_text):
        """Extracts the final recommended action and styles the report."""
        lines = raw_text.split('\n')
        body_lines = []
        action_lines = []
        in_action_section = False
        
        for line in lines:
            lower_line = line.lower()
            if "recommended action" in lower_line or "final verdict" in lower_line:
                in_action_section = True
                parts = line.split(':', 1)
                if len(parts) > 1 and parts[1].strip():
                    action_lines.append(parts[1].replace('**', '').strip())
            elif in_action_section:
                if line.strip():
                    action_lines.append(line.replace('**', '').strip())
            else:
                body_lines.append(line)
                
        if action_lines:
            clean_action = " ".join([l.lstrip('*-•> ').strip() for l in action_lines if l.strip()])
            action_text = clean_action if clean_action else "No explicit action recommended."
        else:
            action_text = "No explicit action recommended."
            
        body_markdown = '\n'.join(body_lines)
        
        # Color coding the verdict roughly based on keywords
        border_col = "#0F172A"
        bg_col = "#F8FAFC"
        lower_action = action_text.lower()
        if "replace" in lower_action or "fail" in lower_action or "stop" in lower_action or "critical" in lower_action or "🔴" in action_text or "🛑" in action_text:
            border_col = "#EF4444"
            bg_col = "#FEF2F2"
        elif "continue" in lower_action or "caution" in lower_action or "🟡" in action_text:
            border_col = "#F59E0B"
            bg_col = "#FFFBEB"
        elif "verify" in lower_action or "proceed" in lower_action or "🟢" in action_text:
            border_col = "#10B981"
            bg_col = "#ECFDF5"
        full_html = f"""<div class="diagnostic-report">

{body_markdown}

<div class="verdict-box" style="border-left-color: {border_col}; background-color: {bg_col};">
    <div class="verdict-title">Final Verdict & Recommended Action</div>
    <div class="verdict-text">{action_text}</div>
</div>
</div>
"""
        st.markdown(full_html, unsafe_allow_html=True)

    _render_styled_diagnosis(diagnosis)

    # Store diagnosis
    st.session_state["last_diagnosis"] = diagnosis
    st.session_state["last_symptoms"] = symptoms

    # Export report button
    _show_export(symptoms, diagnosis)

# Show previous diagnosis if exists
elif "last_diagnosis" in st.session_state:
    st.markdown("### Previous Diagnosis")
    
    # We redefine the helper here securely since it was scoped above
    def _render_styled_diagnosis(raw_text):
        lines = raw_text.split('\n')
        body_lines = []
        action_lines = []
        in_action_section = False
        
        for line in lines:
            lower_line = line.lower()
            if "recommended action" in lower_line or "final verdict" in lower_line:
                in_action_section = True
                parts = line.split(':', 1)
                if len(parts) > 1 and parts[1].strip():
                    action_lines.append(parts[1].replace('**', '').strip())
            elif in_action_section:
                if line.strip():
                    action_lines.append(line.replace('**', '').strip())
            else:
                body_lines.append(line)
                
        if action_lines:
            clean_action = " ".join([l.lstrip('*-•> ').strip() for l in action_lines if l.strip()])
            action_text = clean_action if clean_action else "No explicit action recommended."
        else:
            action_text = "No explicit action recommended."
            
        body_markdown = '\n'.join(body_lines)
        
        border_col = "#0F172A"
        bg_col = "#F8FAFC"
        lower_action = action_text.lower()
        if "replace" in lower_action or "fail" in lower_action or "stop" in lower_action or "critical" in lower_action or "🔴" in action_text or "🛑" in action_text:
            border_col = "#EF4444"
            bg_col = "#FEF2F2"
        elif "continue" in lower_action or "caution" in lower_action or "🟡" in action_text:
            border_col = "#F59E0B"
            bg_col = "#FFFBEB"
        elif "verify" in lower_action or "proceed" in lower_action or "🟢" in action_text:
            border_col = "#10B981"
            bg_col = "#ECFDF5"
        full_html = f"""<div class="diagnostic-report">

{body_markdown}

<div class="verdict-box" style="border-left-color: {border_col}; background-color: {bg_col};">
    <div class="verdict-title">Final Verdict & Recommended Action</div>
    <div class="verdict-text">{action_text}</div>
</div>
</div>
"""
        st.markdown(full_html, unsafe_allow_html=True)

    _render_styled_diagnosis(st.session_state["last_diagnosis"])
    _show_export(st.session_state.get("last_symptoms", ""), st.session_state["last_diagnosis"])
